# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('code', models.IntegerField()),
                ('valid', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('source', models.CharField(max_length=400)),
                ('destination', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
                ('arrival', models.TimeField()),
                ('departure', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Route'),
        ),
    ]
