# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170510_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buscompany',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='buscompany',
            name='latitude',
            field=models.FloatField(default=45.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buscompany',
            name='longitude',
            field=models.FloatField(default=45.7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(default=34.4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(default=43.5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buscompany',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
