# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-05 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180305_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
