# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170511_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=8)),
                ('seats', models.IntegerField()),
                ('model', models.CharField(max_length=400)),
                ('bus_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.BusCompany')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='bus',
            field=models.ForeignKey(default=54, on_delete=django.db.models.deletion.CASCADE, to='myapp.Bus'),
            preserve_default=False,
        ),
    ]
