# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-05 04:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180305_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Wrong phone number format', regex='^(256|254|255)[0-9]{9}$')]),
        ),
    ]
