# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-17 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
