# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170511_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='number_plate',
            new_name='numberPlate',
        ),
    ]
