# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170511_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscompany',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
