# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170511_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='valid',
            field=models.BooleanField(),
        ),
    ]
