# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170511_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=12341234, max_length=40),
            preserve_default=False,
        ),
    ]
