# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20170512_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=400),
        ),
    ]
