# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
