# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-04 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20180305_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='code',
            field=models.UUIDField(auto_created=True, default='1c9feb0c-d6a6-4b86-8f53-f953673437c4', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(auto_created=True, default='1c9feb0c-d6a6-4b86-8f53-f953673437c4', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='code',
            field=models.UUIDField(auto_created=True, unique=True),
        ),
    ]
