# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-04 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20180305_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='code',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True),
        ),
    ]
