# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-04 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20180305_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='code',
            field=models.IntegerField(),
        ),
    ]
